/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rb19.glb -o src/components/Rb19.jsx -r public 
Author: Redgrund (https://sketchfab.com/redgrund)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oracle-red-bull-f1-car-rb19-2023-e4afe46f3aab4b23a418da06fc163821
Title: Oracle Red Bull F1 Car RB19 2023
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function RB19Model(props) {
  const { nodes, materials } = useGLTF("/models/rb19.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.138, 0.324]}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Full_Body_Baked}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Full_Body_Baked}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Full_Body_Baked}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Full_Body_Baked}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Full_Body_Baked}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Full_Body_Baked}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Full_Body_Baked}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/rb19.glb");
